version: '3.8'

services:
  #backend
  backend:
    build:
      context: ./backend/todo
      dockerfile: Dockerfile
    image: xks-todo-backend
    container_name: xksBackend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    networks:
      - todo-network

#frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: xks-todo-frontend
    container_name: xksFrontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
    name: xks-todo-network